import type { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "shared/theme/globals.css";

const inter = Inter({ subsets: ["latin"] });

// eslint-disable-next-line
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{ children: ReactNode }>;

const RootLayout = ({ children }: RootLayoutProps) => (
	<html lang="en">
		<body className={`bg-primary dark:bg-dark-primary flex h-screen w-full text-slate-600 dark:text-white ${inter.className}`}>{children}</body>
	</html>
);

export default RootLayout;
